/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx,mdx}",
    "./registry/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: "var(--primary)",
        secondary: "var(--secondary)",
        tertiary: "var(--tertiary)",
        neutral: "var(--neutral)",
        surface: "var(--surface)",
        "on-surface": "var(--on-surface)",
        error: "var(--error)",
        border: "var(--border)",
        "primary-90": "var(--primary-90)",
        "primary-70": "var(--primary-70)",
        "primary-50": "var(--primary-50)",
        "primary-20": "var(--primary-20)",
        "primary-60": "var(--primary-60)",
        "primary-80": "var(--primary-80)",
        "secondary-90": "var(--secondary-90)",
        "secondary-70": "var(--secondary-70)",
        "secondary-50": "var(--secondary-50)",
        "secondary-20": "var(--secondary-20)",
      },
      borderColor: {
        border: "var(--border)",
      },
      borderRadius: {
        none: "0px",
        sm: "4px",
        md: "8px",
        lg: "12px",
        xl: "16px",
        full: "9999px",
      },
      spacing: {
        xs: "8px",
        sm: "24px",
        md: "40px",
        lg: "80px",
        xl: "128px",
        gutter: "24px",
        margin: "24px",
      },
      fontFamily: {
        sans: ["ui-sans-serif", "system-ui", "-apple-system", "BlinkMacSystemFont", "sans-serif"],
        serif: ["Lora", "Georgia", "Cambria", "Times New Roman", "Times", "serif"],
        mono: ["JetBrains Mono", "Fira Code", "monospace"],
      },
      fontSize: {
        "headline-display": ["32px", { lineHeight: "38px", fontWeight: "700" }],
        "headline-lg": ["26px", { lineHeight: "31px", fontWeight: "700" }],
        "headline-md": ["21px", { lineHeight: "24px", fontWeight: "500" }],
        "headline-sm": ["17px", { lineHeight: "20px", fontWeight: "500" }],
        "body-lg": ["16px", { lineHeight: "25px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "22px", fontWeight: "400" }],
        "body-sm": ["12px", { lineHeight: "18px", fontWeight: "400" }],
        "label-lg": ["16px", { lineHeight: "20px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "18px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500", letterSpacing: "0.04em" }],
        "caption": ["10px", { lineHeight: "12px", fontWeight: "400", letterSpacing: "0.08em" }],
        "mono-annotation": ["11px", { lineHeight: "14px", fontWeight: "400", letterSpacing: "0.02em" }],
      },
    },
  },
  plugins: [],
}
