import type { Career } from '@/types';

export const careers: Career[] = [
  {
    id: 'career-1',
    title: 'Frontend Developer',
    slug: 'frontend-developer',
    field: 'Technology',
    subfield: 'Web Development',
    description: 'Build web applications using React, HTML, CSS, and modern web standards.',
    shortDescription: 'Build frontend web applications.',
    overview: 'Frontend Developer Overview',
    whatItDoes: 'Frontend Developer What It Does',
    avgSalaryIndia: '6-12 LPA',
    avgSalaryGlobal: '$80,000 - $120,000',
    demandTrend: 'rising',
    timeToJobReady: '6 months',
    skillsRequired: ['react', 'javascript', 'html', 'css', 'typescript'],
    stages: [],
    relatedCareers: [],
    tags: ['web', 'frontend', 'ui', 'react'],
    aliases: ['frontend developer', 'frontend engineer', 'react developer', 'nextjs developer', 'ui developer', 'web developer'],
    icon: 'web',
    recommendedResourceIds: [],
    recommendedJobs: []
  },
  {
    id: 'career-2',
    title: 'Backend Developer',
    slug: 'backend-developer',
    field: 'Technology',
    subfield: 'Web Development',
    description: 'Build robust server-side APIs, database schemas, and microservices.',
    shortDescription: 'Build backend server-side applications.',
    overview: 'Backend Developer Overview',
    whatItDoes: 'Backend Developer What It Does',
    avgSalaryIndia: '7-14 LPA',
    avgSalaryGlobal: '$90,000 - $130,000',
    demandTrend: 'rising',
    timeToJobReady: '8 months',
    skillsRequired: ['node.js', 'express', 'postgresql', 'python', 'databases', 'apis'],
    stages: [],
    relatedCareers: [],
    tags: ['server', 'backend', 'node', 'python', 'database'],
    aliases: ['backend developer', 'backend engineer', 'node developer', 'nodejs developer', 'python developer'],
    icon: 'server',
    recommendedResourceIds: [],
    recommendedJobs: []
  },
  {
    id: 'career-3',
    title: 'AI Engineer',
    slug: 'ai-engineer',
    field: 'Technology',
    subfield: 'Artificial Intelligence',
    description: 'Build machine learning pipelines, fine-tune neural networks, and integrate LLMs.',
    shortDescription: 'Build and deploy machine learning models.',
    overview: 'AI Engineer Overview',
    whatItDoes: 'AI Engineer What It Does',
    avgSalaryIndia: '10-25 LPA',
    avgSalaryGlobal: '$130,000 - $200,000',
    demandTrend: 'rising',
    timeToJobReady: '12 months',
    skillsRequired: ['python', 'pytorch', 'scikit-learn', 'llms', 'machine learning'],
    stages: [],
    relatedCareers: [],
    tags: ['ai', 'machine-learning', 'python', 'llm'],
    aliases: ['ai engineer', 'ml engineer', 'machine learning engineer', 'data scientist'],
    icon: 'cpu',
    recommendedResourceIds: [],
    recommendedJobs: []
  },
  {
    id: 'career-4',
    title: 'DevOps Engineer',
    slug: 'devops-engineer',
    field: 'Technology',
    subfield: 'Cloud Infrastructure',
    description: 'Automate build pipelines, monitor infrastructure, and manage container deployments.',
    shortDescription: 'Manage cloud infrastructure and automation.',
    overview: 'DevOps Engineer Overview',
    whatItDoes: 'DevOps Engineer What It Does',
    avgSalaryIndia: '8-18 LPA',
    avgSalaryGlobal: '$100,000 - $150,000',
    demandTrend: 'rising',
    timeToJobReady: '10 months',
    skillsRequired: ['docker', 'kubernetes', 'aws', 'cicd', 'linux'],
    stages: [],
    relatedCareers: [],
    tags: ['cloud', 'devops', 'docker', 'aws', 'infrastructure'],
    aliases: ['devops engineer', 'cloud engineer', 'site reliability engineer', 'sre'],
    icon: 'cloud',
    recommendedResourceIds: [],
    recommendedJobs: []
  },
  {
    id: 'career-5',
    title: 'Mobile Developer',
    slug: 'mobile-developer',
    field: 'Technology',
    subfield: 'Mobile Applications',
    description: 'Design and build cross-platform mobile apps using React Native, Flutter, Swift, or Kotlin.',
    shortDescription: 'Build iOS and Android mobile apps.',
    overview: 'Mobile Developer Overview',
    whatItDoes: 'Mobile Developer What It Does',
    avgSalaryIndia: '6-14 LPA',
    avgSalaryGlobal: '$85,000 - $125,000',
    demandTrend: 'stable',
    timeToJobReady: '6 months',
    skillsRequired: ['react native', 'flutter', 'swift', 'kotlin', 'mobile'],
    stages: [],
    relatedCareers: [],
    tags: ['mobile', 'react-native', 'flutter', 'ios', 'android'],
    aliases: ['mobile developer', 'react native developer', 'flutter developer', 'ios developer', 'android developer'],
    icon: 'smartphone',
    recommendedResourceIds: [],
    recommendedJobs: []
  },
  {
    id: 'career-6',
    title: 'Data Scientist',
    slug: 'data-scientist',
    field: 'Technology',
    subfield: 'Data & Analytics',
    description: 'Analyze complex datasets to build predictive models and derive business insights.',
    shortDescription: 'Analyze data and build predictive models.',
    overview: 'Data Scientist Overview',
    whatItDoes: 'Data Scientist What It Does',
    avgSalaryIndia: '9-20 LPA',
    avgSalaryGlobal: '$110,000 - $160,000',
    demandTrend: 'rising',
    timeToJobReady: '9 months',
    skillsRequired: ['python', 'sql', 'statistics', 'pandas', 'machine learning'],
    stages: [],
    relatedCareers: [],
    tags: ['data', 'science', 'python', 'sql', 'analysis'],
    aliases: ['data scientist', 'data analyst', 'business analyst'],
    icon: 'database',
    recommendedResourceIds: [],
    recommendedJobs: []
  },
  {
    id: 'career-7',
    title: 'Cybersecurity Analyst',
    slug: 'cybersecurity-analyst',
    field: 'Technology',
    subfield: 'Information Security',
    description: 'Protect systems, networks, and data from cyber threats and security breaches.',
    shortDescription: 'Secure cloud networks and systems.',
    overview: 'Cybersecurity Analyst Overview',
    whatItDoes: 'Cybersecurity Analyst What It Does',
    avgSalaryIndia: '7-15 LPA',
    avgSalaryGlobal: '$90,000 - $140,000',
    demandTrend: 'rising',
    timeToJobReady: '8 months',
    skillsRequired: ['security', 'linux', 'networks', 'wireshark', 'ethical hacking'],
    stages: [],
    relatedCareers: [],
    tags: ['security', 'networking', 'linux', 'cyber'],
    aliases: ['cybersecurity analyst', 'security engineer', 'penetration tester'],
    icon: 'shield',
    recommendedResourceIds: [],
    recommendedJobs: []
  },
  {
    id: 'career-8',
    title: 'UX Designer',
    slug: 'ux-designer',
    field: 'Design',
    subfield: 'User Experience',
    description: 'Create user-centered interface layouts, wireframes, and design systems in Figma.',
    shortDescription: 'Design user interfaces and experiences.',
    overview: 'UX Designer Overview',
    whatItDoes: 'UX Designer What It Does',
    avgSalaryIndia: '6-15 LPA',
    avgSalaryGlobal: '$80,000 - $130,000',
    demandTrend: 'stable',
    timeToJobReady: '6 months',
    skillsRequired: ['figma', 'wireframing', 'user research', 'ui design', 'prototyping'],
    stages: [],
    relatedCareers: [],
    tags: ['design', 'ui', 'ux', 'figma'],
    aliases: ['ux designer', 'ui designer', 'product designer', 'ui ux designer'],
    icon: 'palette',
    recommendedResourceIds: [],
    recommendedJobs: []
  },
  {
    id: 'career-9',
    title: 'QA Tester',
    slug: 'qa-tester',
    field: 'Technology',
    subfield: 'Quality Assurance',
    description: 'Verify software functionality, write test scripts, and build automated testing systems.',
    shortDescription: 'Verify code quality and test applications.',
    overview: 'QA Tester Overview',
    whatItDoes: 'QA Tester What It Does',
    avgSalaryIndia: '4-9 LPA',
    avgSalaryGlobal: '$60,000 - $95,000',
    demandTrend: 'stable',
    timeToJobReady: '4 months',
    skillsRequired: ['selenium', 'cypress', 'testing', 'qa', 'playwright'],
    stages: [],
    relatedCareers: [],
    tags: ['qa', 'testing', 'automation'],
    aliases: ['qa tester', 'qa engineer', 'automation engineer', 'test engineer'],
    icon: 'check-square',
    recommendedResourceIds: [],
    recommendedJobs: []
  },
  {
    id: 'career-10',
    title: 'Full Stack Developer',
    slug: 'full-stack-developer',
    field: 'Technology',
    subfield: 'Web Development',
    description: 'Build end-to-end web applications, designing both responsive frontends and backend servers.',
    shortDescription: 'Build complete frontend and backend applications.',
    overview: 'Full Stack Developer Overview',
    whatItDoes: 'Full Stack Developer What It Does',
    avgSalaryIndia: '8-18 LPA',
    avgSalaryGlobal: '$95,000 - $140,000',
    demandTrend: 'rising',
    timeToJobReady: '9 months',
    skillsRequired: ['react', 'node.js', 'postgresql', 'express', 'javascript', 'typescript'],
    stages: [],
    relatedCareers: [],
    tags: ['web', 'frontend', 'backend', 'fullstack'],
    aliases: ['full stack developer', 'fullstack developer', 'fullstack engineer', 'full stack engineer'],
    icon: 'layers',
    recommendedResourceIds: [],
    recommendedJobs: []
  }
];
